EASIER_MAP: dict[str, str] = {
    "abc": "Practice tracing single letters — tap each letter and listen to its sound",
    "math": "Count objects from 1 to 5 — point at each animal and say the number",
    "memory": "Try a smaller 2x3 card grid — find 3 matching animal pairs",
    "drawing": "Draw with a big brush and bright colors — there's no wrong way to draw!",
    "shapes": "Learn shapes first — tap each shape and hear its name",
    "rhymes": "Try the Find the Rhyme mode — pick from 4 choices",
    "emotions": "Start with Learn Feelings — tap each face to explore emotions",
    "wordbuilder": "Try Easy mode with 3-letter words — cat, dog, sun",
    "colors": "Start with Learn Colors — tap each color and see what objects are that color",
    "animals": "Try Animal Sounds — pick which animal makes each sound",
    "story": "Start with a 3-step story — put the cards in the right order",
    "trace": "Trace simple letters like I, L, and T first — follow the green dot",
    "fruits": "Start with Learn — tap each fruit or veggie to hear its name",
    "opposites": "Browse the Learn tab — see each opposite pair side by side",
    "spotdiff": "Start with the Farm Scene — spot 3 differences to begin",
    "numbertrace": "Trace number 1 first — it's just one straight line down!",
    "sightwords": "Try Flash Cards — flip each card to see the word in a sentence",
    "bodyparts": "Browse the Learn tab — tap each body part to hear a fun fact",
    "daysmonths": "Start with the Days tab — tap each day and learn its emoji",
    "subtraction": "Start with small numbers — tap away 1 or 2 animals first",
    "vehicles": "Start with Learn — tap each vehicle to hear its sound and fun fact",
    "clock": "Start with Learn — see o'clock times with daily activities",
    "shadow": "Look at the overall shape of the shadow before choosing!",
    "phonics": "Start with clear emojis — listen to the name and find the first letter",
    "sizeorder": "Try the first group — arrange 3 items from smallest to biggest",
    "helpers": "Browse Learn mode — tap each helper to see their tools and vehicle",
    "foodgroups": "Start with Learn — see what foods belong to each group",
    "sinkorflout": "Think about heavy vs light — rocks sink, feathers float!",
    "skipcounting": "Start with count-by-10s — 10, 20, 30 are the easiest!",
    "wordfamilies": "Try the -at family — cat, bat, hat all sound alike at the end",
    "music": "Start with Learn — tap each instrument to see its name and fun fact",
    "nature": "Start with Learn → Living — flowers, trees, and animals are all living!",
    "directions": "Start with Learn — tap each arrow and say the direction out loud",
    "weather": "Start with Learn — tap each weather type and see what clothes to wear",
    "patterns": "Start with ABAB patterns — they only use 2 items!",
    "money": "Start with Learn — tap each coin to see its value",
    "habitats": "Start with Learn — explore each habitat and its animals",
    "fractions": "Start with Learn — tap a food and see whole, half and quarter",
    "abcorder": "Start with the Chart — tap each letter and find where it is",
    "safety": "Start with Learn → Road — learn to look both ways before crossing",
    "measurement": "Start with Compare → Tall/Short — which is taller?",
    "space": "Start with Explore — tap each planet to learn a fun fact",
    "sentences": "Start with Build — tap one word from each box to make a sentence",
    "ordinal": "Start with Learn — see 1st, 2nd, 3rd with a race of animals",
    "numberline": "Start with Learn — tap each number on the line from 1 to 10",
    "moreorless": "Start with Compare — which group of dots has more?",
    "tenframes": "Start with Learn — count the dots in the ten frame",
    "numberbonds": "Start with bonds to 5 — they use smaller numbers",
    "numberwords": "Start with Learn — see each number word matched to its digit",
    "syllables": "Start with Learn — clap along as you say each word out loud",
    "compound": "Start with Learn — see how two small words make one big word",
    "plurals": "Start with Learn — see how adding -s changes one to many",
    "verbs": "Start with Learn — tap each action emoji to see the word",
    "prepositions": "Start with Learn — see the cat sitting ON the box",
    "cvc": "Start with Learn — look at the three colored letter boxes",
    "plantlife": "Start with Learn — see how a seed grows into a plant",
    "animalcycle": "Start with Learn — explore each animal's life cycle",
    "senses": "Start with Learn — tap each sense to see what it does",
    "pushpull": "Think: do you push or pull a door open?",
    "temperature": "Start with Learn — tap Hot, Warm, and Cold to see each group",
    "seasonschange": "Start with Learn — tap each season to see what it looks like",
    "habits": "Start with Learn — explore each healthy habit",
    "routine": "Start with Learn — see the daily routine from morning to night",
    "babyanimals": "Start with Learn — tap each adult animal to meet its baby",
    "homes": "Start with Learn — see where each animal lives",
    "worldfoods": "Start with Learn — tap each food to see where it comes from",
    "shapes3d": "Start with Learn — tap each 3D shape to see its real-world examples",
    "maps": "Start with Learn — explore the simple picture map",
    "colorwords": "Start with Learn — see each color word in its own color",
    "sizewords": "Start with Learn — compare the big and small side by side",
    "sortcolors": "Look at the color of the object — which bucket matches?",
    "scenarios": "Think about what a kind and safe choice looks like",
    "rhymestory": "Listen to the first line — what word sounds like the last word?",
}

SAME_MAP: dict[str, str] = {
    "abc": "Keep exploring letters — try matching uppercase to lowercase",
    "math": "Keep counting animals up to 10 — great work so far!",
    "memory": "Keep playing the 3x4 memory grid — you're getting better each time",
    "drawing": "Keep creating art — try mixing new colors today",
    "shapes": "Keep practicing shape identification — try the Match Outline mode",
    "rhymes": "Keep finding rhymes — try the Rhyme Sort challenge",
    "emotions": "Keep matching emotions — try to explain each feeling out loud",
    "wordbuilder": "Keep building words — aim for a longer streak!",
    "colors": "Keep exploring colors — try the Mix Colors lab and see what new colors you can make",
    "animals": "Keep learning about animals — try Where Do I Live? for a new challenge",
    "story": "Keep sequencing stories — try a new story each round",
    "trace": "Keep tracing — practice makes perfect! Try curved letters next",
    "fruits": "Keep sorting — try the Compare Size tab to guess which is bigger!",
    "opposites": "Keep matching opposites — aim for 10 in a row!",
    "spotdiff": "Keep spotting differences — try to find them all without any wrong taps!",
    "numbertrace": "Keep tracing — try numbers 4, 7, and 8 which have more curves!",
    "sightwords": "Keep reading — try the Find It tab to spot words in sentences",
    "bodyparts": "Keep learning — try the Quiz tab to test what you know!",
    "daysmonths": "Keep practicing — try the Order Game to put days in the right order",
    "subtraction": "Keep going — try bigger numbers like 8 minus 3!",
    "vehicles": "Keep sorting — try to get all 14 vehicles into the right zone!",
    "clock": "Keep reading clocks — try the Quiz tab to test yourself!",
    "shadow": "Keep matching — can you beat your high score?",
    "phonics": "Keep finding starting sounds — try all 26 letters!",
    "sizeorder": "Keep ordering — try all 6 groups with different animals and objects!",
    "helpers": "Keep matching tools — try the vehicle quiz next!",
    "foodgroups": "Keep sorting — try to place all 20 foods without any mistakes!",
    "sinkorflout": "Keep predicting — try to explain why each object sinks or floats!",
    "skipcounting": "Keep counting — try 2s and 5s for more of a challenge!",
    "wordfamilies": "Keep building words — try every word family!",
    "music": "Keep exploring — try the Sort tab to group instruments by family!",
    "nature": "Keep sorting living and non-living — try the Quiz tab to test yourself!",
    "directions": "Keep practicing — try the Move Game to guide the chick around the grid!",
    "weather": "Keep learning — try Dress Up to pick the right clothes for each weather!",
    "patterns": "Keep going — try AABB patterns for a new challenge!",
    "money": "Keep practicing — try Count It to add up coins!",
    "habitats": "Keep exploring — try Sort mode to place each animal in its home!",
    "fractions": "Keep learning — try Name It to identify fractions from pictures!",
    "abcorder": "Keep practicing — try What's Next to find the letter that comes after!",
    "safety": "Keep learning — try Safe or Not to test your safety knowledge!",
    "measurement": "Keep comparing — try the Ruler game to count units!",
    "space": "Keep exploring — try the Planet Quiz to name each planet!",
    "sentences": "Keep building — try Arrange to put scrambled sentences in order!",
    "ordinal": "Keep practicing ordinal numbers — try ordering 6 items!",
    "numberline": "Keep jumping on the number line — try bigger jumps!",
    "moreorless": "Keep comparing — try groups with closer numbers like 7 vs 8!",
    "tenframes": "Keep filling ten frames — try to picture the frame in your head!",
    "numberbonds": "Keep finding bonds — try all the ways to make 10!",
    "numberwords": "Keep reading number words — try spelling them from memory!",
    "syllables": "Keep clapping syllables — try longer words like 'elephant'!",
    "compound": "Keep building compound words — can you think of more?",
    "plurals": "Keep making plurals — try irregular ones like 'child → children'!",
    "verbs": "Keep practicing verbs — act out each action word!",
    "prepositions": "Keep learning positions — try describing where things are in your room!",
    "cvc": "Keep reading CVC words — try the Build tab to spell them!",
    "plantlife": "Keep learning about plants — try the Quiz tab!",
    "animalcycle": "Keep exploring life cycles — try ordering the stages!",
    "senses": "Keep learning the senses — try the Quiz tab to test yourself!",
    "pushpull": "Keep sorting push and pull — try all 16 actions!",
    "temperature": "Keep sorting temperatures — try the Which is Hotter? challenge!",
    "seasonschange": "Keep learning seasons — try the clothing quiz!",
    "habits": "Keep learning healthy habits — try to practice one today!",
    "routine": "Keep learning the routine — can you say it from memory?",
    "babyanimals": "Keep learning baby names — try the Match quiz!",
    "homes": "Keep matching homes — try to remember all 12 pairs!",
    "worldfoods": "Keep exploring world foods — try the country quiz!",
    "shapes3d": "Keep learning 3D shapes — try Find It and Name It tabs!",
    "maps": "Keep exploring the map — try reading it from a different spot!",
    "colorwords": "Keep reading color words — try both quiz modes!",
    "sizewords": "Keep learning size words — try the Compare and Match tabs!",
    "sortcolors": "Keep sorting — try to get all 24 items right without a mistake!",
    "scenarios": "Keep making good choices — try all 12 scenarios!",
    "rhymestory": "Keep completing rhymes — read the full poem out loud!",
}

HARDER_MAP: dict[str, str] = {
    "abc": "Try spelling 4-letter words — you're ready for the next level!",
    "math": "Practice addition up to 15 — count two groups of animals together",
    "memory": "Challenge yourself with the 4x4 grid — 8 pairs to match!",
    "drawing": "Try tracing a shape outline — draw a house or a star",
    "shapes": "Try the Match Outline challenge — match silhouettes to solid shapes",
    "rhymes": "Try Rhyme Sort — separate all the rhyming words from the non-rhymes",
    "emotions": "Play the story-matching game — guess the feeling from the situation",
    "wordbuilder": "Try Hard mode with 5-letter words like 'tiger' and 'cloud'!",
    "colors": "Try Find the Color — identify object colors without any hints",
    "animals": "Try Baby Animals — learn what each baby animal is called",
    "story": "Try putting all 4-step stories in order on the first try without mistakes",
    "trace": "Try the curved and diagonal letters: C, S, A, B, and X — the trickiest ones!",
    "fruits": "Try Sort mode — race to sort all 18 fruits and veggies correctly!",
    "opposites": "Challenge yourself — describe each opposite in your own words!",
    "spotdiff": "Try the Space and Jungle puzzles — they have 3-4 tricky differences!",
    "numbertrace": "Challenge yourself with 6, 8, and 9 — the hardest numbers to trace!",
    "sightwords": "Try the Spell It tab — build sight words from letter tiles!",
    "bodyparts": "Challenge: name every body part and say one thing it helps you do!",
    "daysmonths": "Try the Order Game with months — can you name the season for each one?",
    "subtraction": "Challenge: solve subtraction without tapping the animals — picture it in your head!",
    "vehicles": "Can you name a vehicle for each zone without looking at the cards?",
    "clock": "Try half past times in the Quiz — they are trickier than o'clock!",
    "shadow": "Challenge: guess before the answer reveals — trust your eyes!",
    "phonics": "Challenge: sound out each word before looking at the choices!",
    "sizeorder": "Challenge: can you complete all 6 groups without any mistakes?",
    "helpers": "Challenge: describe what each helper does before tapping the card!",
    "foodgroups": "Challenge: name a food from each group that isn't in the game!",
    "sinkorflout": "Challenge: predict before dropping — try 5 in a row without a mistake!",
    "skipcounting": "Challenge: count by 2s all the way to 20 from memory!",
    "wordfamilies": "Challenge: can you think of more words in each family not shown in the game?",
    "music": "Challenge: listen for the sound, then name the instrument and its family!",
    "nature": "Challenge: explain to someone why living things are different from non-living things!",
    "directions": "Challenge: complete the Move Game 3 times without any wrong moves!",
    "weather": "Challenge: explain what season each weather belongs to without looking!",
    "patterns": "Challenge: try ABC patterns — three different items in a row!",
    "money": "Challenge: add up 4 coins in your head before tapping the answer!",
    "habitats": "Challenge: name 2 animals from each habitat from memory!",
    "fractions": "Challenge: explain what half and quarter mean to a grown-up!",
    "abcorder": "Challenge: try ordering 5 letters — the longest challenge!",
    "safety": "Challenge: make up your own safety rule for a new situation!",
    "measurement": "Challenge: use the ruler to measure something in real life at home!",
    "space": "Challenge: name all 8 planets in order from the Sun without looking!",
    "sentences": "Challenge: arrange a whole sentence correctly on your first try!",
    "ordinal": "Challenge: name the ordinal position of every animal in a race!",
    "numberline": "Challenge: jump by 2s on the number line without looking!",
    "moreorless": "Challenge: can you tell more or less without counting — just looking?",
    "tenframes": "Challenge: fill a ten frame and write the matching number!",
    "numberbonds": "Challenge: say all the bonds of 10 from memory — 0+10, 1+9...",
    "numberwords": "Challenge: write all number words from one to ten without help!",
    "syllables": "Challenge: find 3 things in the room and clap their syllables!",
    "compound": "Challenge: make up your own compound word!",
    "plurals": "Challenge: find 5 objects and say their plurals out loud!",
    "verbs": "Challenge: act out each verb and use it in a full sentence!",
    "prepositions": "Challenge: hide a toy and describe where it is using three prepositions!",
    "cvc": "Challenge: build 5 CVC words from scratch without any hints!",
    "plantlife": "Challenge: explain the full life cycle of a flower from memory!",
    "animalcycle": "Challenge: explain a butterfly's life cycle to a grown-up!",
    "senses": "Challenge: close your eyes and identify 5 things using your other senses!",
    "pushpull": "Challenge: find 3 things at home that you push and 3 that you pull!",
    "temperature": "Challenge: sort all items from coldest to hottest in your mind!",
    "seasonschange": "Challenge: describe all four seasons and what you wear in each!",
    "habits": "Challenge: make a healthy habits checklist for your whole day!",
    "routine": "Challenge: explain your full daily routine to a grown-up from memory!",
    "babyanimals": "Challenge: name the baby for all 12 animals without any hints!",
    "homes": "Challenge: name the home for all 12 animals from memory!",
    "worldfoods": "Challenge: name the country for every food without looking!",
    "shapes3d": "Challenge: find one real-world example of each 3D shape in your home!",
    "maps": "Challenge: draw your own simple map of your bedroom!",
    "colorwords": "Challenge: read all 10 color words and spell each one out loud!",
    "sizewords": "Challenge: use 5 size words to describe things around you!",
    "sortcolors": "Challenge: sort all 24 items without a single mistake!",
    "scenarios": "Challenge: make up your own good-choice scenario and act it out!",
    "rhymestory": "Challenge: make up your own rhyming couplet about an animal!",
}

WEIGHTS = [0.30, 0.20, 0.15, 0.10, 0.08, 0.06, 0.04, 0.03, 0.02, 0.02]


class TutorEngine:
    def weighted_avg(self, scores: list[float]) -> float:
        if not scores:
            return 0.5
        pairs = list(zip(scores, WEIGHTS[: len(scores)]))
        total_weight = sum(w for _, w in pairs)
        return sum(s * w for s, w in pairs) / total_weight

    def recommend(self, skill: str, scores: list[float]) -> dict:
        avg = self.weighted_avg(scores)
        if avg < 0.60:
            return {
                "action": "easier",
                "next_activity": EASIER_MAP.get(skill, EASIER_MAP["abc"]),
                "current_avg": round(avg, 3),
            }
        elif avg > 0.85:
            return {
                "action": "harder",
                "next_activity": HARDER_MAP.get(skill, HARDER_MAP["abc"]),
                "current_avg": round(avg, 3),
            }
        else:
            return {
                "action": "same",
                "next_activity": SAME_MAP.get(skill, SAME_MAP["abc"]),
                "current_avg": round(avg, 3),
            }
